- name: Configure error notifications for systemd services
  hosts: "{{ target if target is defined else 'production' }}"
  tasks:
    - name: Install ssmtp
      become: true
      become_user: root
      ansible.builtin.apt:
        name: ssmtp
    - name: Configure ssmtp
      become: true
      become_user: root
      ansible.builtin.template:
        src: files/ssmtp.conf.j2
        dest: /etc/ssmtp/ssmtp.conf
        mode: '600'
    - name: Create error notify service
      become: true
      become_user: root
      ansible.builtin.template:
        src: files/error-notify@.service.j2
        dest: /etc/systemd/system/error-notify@.service
        mode: '644'
    - name: Daemon reload
      become: true
      become_user: root
      ansible.builtin.systemd:
        daemon_reload: true
