- name: Setup services
  hosts: "{{ target if target is defined else 'production' }}"
  vars:
    services:
      # - name: bitwarden
      #   internalport: 8280
      # - name: freshrss
      #   internalport: 8281
      # - name: wallabag
      #   internalport: 8282
      - name: mealie
        internalport: 8283
      # - name: vikunja
      #   internalport: 8284
      # - name: vikunja_backend
      #   internalport: 8285
      # - name: mealie-kroger
      #   internalport: 8286
      # - name: recycling
      #   internalport: 3000
  tasks:
    - name: Add docker compose services
      ansible.builtin.include_role:
        name: dockercomposeservice
      vars:
        dockercomposeservice_name: "{{ item.name }}"
      loop:
        "{{ services }}"
    - name: Add nginx configurations
      become: true
      become_user: root
      ansible.builtin.template:
        src: templates/nginx_server.j2
        dest: "/etc/nginx/sites-available/{{ item.name }}"
        mode: '777'
      vars:
        nginx_server_name: "{{ item.name }}"
        nginx_server_local_port: "{{ item.internalport }}"
      loop:
        "{{ services }}"
    - name: Make nginx sites enabled
      become: true
      become_user: root
      ansible.builtin.file:
        src: /etc/nginx/sites-available/{{ item.name }}
        dest: /etc/nginx/sites-enabled/{{ item.name }}
        state: link
      loop:
        "{{ services }}"
      notify:
        - Reload nginx

  handlers:
    - name: Reload nginx
      become: true
      become_user: root
      ansible.builtin.command: nginx -s reload
      changed_when: true
