---
- name: Copy timer file
  become: true
  become_user: root
  ansible.builtin.template:
    src: templates/timer.timer.j2
    dest: /etc/systemd/system/{{ systemdtimer_servicename }}.timer
    mode: '644'
- name: Copy service file
  become: true
  become_user: root
  ansible.builtin.template:
    src: templates/service.service.j2
    dest: /etc/systemd/system/{{ systemdtimer_servicename }}.service
    mode: '644'
- name: Enable and start timer
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: "{{ systemdtimer_servicename }}.timer"
    state: started
    daemon_reload: true
    enabled: "{{ systemdtimer_enabled | default(true) }}"
