version: '3'

services:
  frontend:
    image: vikunja/frontend
    restart: unless-stopped
    ports:
      - 8284:80
    environment:
      VIKUNJA_API_URL: https://vikunja_backend.samacohen.com/api/v1
